
import Body from "@/components/Body";
import { AddProductComponent } from "@/components/addProductComponent";
import { ProductType } from "@/components/addProductComponent/model";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Warehouse | NextJS 14 server actions',
  description: 'Generated by create next app',
}

export default async function Warehouse() {
  const res = await fetch(
    "https://6586e161468ef171392ee908.mockapi.io/api/v1/products",
    {
      cache: "no-cache",
      next: {
        tags: ["products"],
      }
    }
  );

  const products: ProductType[] = await res.json();

  return (
    <Body>
      <h1 className="text-3xl font-bold text-center">Product Warehouse</h1>
      <AddProductComponent products={products} />
    </Body>
  );
}
